name: recommendation-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scikit-learn>=0.24.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - jupyter>=1.0.0
  - pip>=21.0
  - pytest>=6.0
  - flake8>=3.9.0
  - pylint>=2.8.0
  - pip:
    - kaggle>=1.5.0
